@startuml オブジェクト図
left to right direction

object "<u>車:車</u>" as c
object "<u>タイヤ1:タイヤ</u>" as t1
object "<u>タイヤ2:タイヤ</u>" as t2
object "<u>タイヤ3:タイヤ</u>" as t3
object "<u>タイヤ4:タイヤ</u>" as t4

c -- t1
c -- t2
c -- t3
c -- t4
@enduml