@startuml ユースケース図
rectangle 盛岡システム(株) {
    actor 人事担当者
    actor 社員
    rectangle 従業員システム {
        usecase 社員情報の登録
        usecase 社員情報の参照
        usecase 変更届の提出
        usecase 変更届の確認
        usecase 社員情報の修正
    }
    人事担当者 --> 社員情報の登録
    人事担当者 --> 社員情報の修正
    人事担当者 --> 変更届の確認
    社員情報の修正 ..> 変更届の確認 : << include >>
    変更届の確認 ..> 変更届の提出 : << include >>
    社員 --> 社員情報の参照
    社員 --> 変更届の提出
}
